### PR TITLE
Fixes #147

### LINKED ISSUE #147: Unable to set default directory for views
Hello, I am unable to set default `views` directory.

OS: Ubuntu 15.04
Node: 4.0.0

I am in app directory (...).
When running `node server/server.js`, it ignores 
`app.set('views', path.join(__dirname, 'views'));` from `server.js` and tries to load 
`.../views/layouts/main.handlebars` instead `.../server/views/layouts/main.handlebars`

```shell
.
└── server
    ├── server.js
    └── views
        ├── home.handlebars
        └── layouts
            └── main.handlebars
```

server.js
```javascript
'use strict';

var path = require('path');
var express = require('express');
var exphbs  = require('express-handlebars');
var app = express();

// Rendering engine setup
app.engine('handlebars', exphbs({defaultLayout: 'main'}));
app.set('view engine', 'handlebars');
app.set('views', path.join(__dirname, 'views'));
console.log(path.join(__dirname, 'views'));

// Routes
app.get('/', function (req, res) {
    res.render('home');
});

app.listen(8888);
```

EDIT: it works when i am in (`.../server/` directory) and `node server.js`, it is wierd, becouse it should get right path from `app.locals.setting.views` variable.

### PR DESCRIPTION
**Pull request by camabeh**

### CODE REVIEW

**Comment by samuelfine** [comment]
:+1: Keeping `/partials` and `/layouts` relative to `/views` makes sense to me.

**Comment by sahat** [comment]
Looks good :+1:

**Comment by kristofferostlund** [comment]
Any progress on this?

**Comment by kevmo** [comment]
@camabeh should write a better description, and then this should be merged?

**Comment by sahat** [comment]
I don't have NPM publish rights, so in the meantime you can use install express-handlebars the following way:

```json
"dependencies": {
    "express-handlebars": "ericf/express-handlebars"
}
```

**Comment by gustavoaca1997** [comment]
this is already in the NPM package? Because I have this same [issue](https://github.com/ericf/express-handlebars/issues/195)

**Pull request merged**
