### PR TITLE
🚨 Security Update: handlebars dependency 🚨

### PR DESCRIPTION
**Pull request by asos-albinotonnina**
A vulnerability has been found in handlebars@4.0.12

This PR updated to @4.0.13

vulnerability report: https://snyk.io/vuln/SNYK-JS-HANDLEBARS-173692

commit: https://github.com/wycats/handlebars.js/commit/7372d4e9dffc9d70c09671aa28b9392a1577fd86

### CODE REVIEW

**Comment by asos-albinotonnina** [comment]
Thank you so much for the approval @benjipott 
Do you think you're going to publish on npm?
Last version, 3.0.0, is 3 years old..

**Comment by benjipott** [comment]
I don't have any access to merge or publish, sorry

**Comment by sahat** [comment]
I have published a new version 3.0.1 to NPM with the updated dependencies.

**Comment by asos-albinotonnina** [comment]
Great news! Thank you very much @sahat, much appreciated!

**Pull request merged**
