### PR TITLE
Provide default for defaultLayout

### PR DESCRIPTION
**Pull request by jfbrennan**
It pains me to see this:
```
app.engine('handlebars', exphbs({defaultLayout: 'main'}));
```

This PR makes express-handlebars default to `main` if `defaultLayout` is not set. That way you can do:
```
app.engine('handlebars', exphbs());
```

### CODE REVIEW

**Comment by UziTech** [comment]
shouldn't the default be `'main'`?

**Comment by jfbrennan** [comment]
We can name it whatever, happy to go with ‘main’ if that’ll get this PR merged

**Comment by jfbrennan** [comment]
@ericf any objections to this PR?

**Comment by jfbrennan** [comment]
@UziTech @ericf @sahat can I get a review? This is a simple backwards-compatible change that completes the "sensible defaults" story for express-handlebars.

**Review by UziTech — APPROVED** [review]

**Comment by jfbrennan** [comment]
Thanks @UziTech when do you expect the next release to happen?

**Comment by UziTech** [comment]
I don't have the ability to merge pull requests and it looks like @ericf has stepped away from the project. So @sahat is the only active contributor with the ability to merge PRs and release new versions.

**Comment by jfbrennan** [comment]
@UziTech @sahat now that this suggestion has been approved I updated the docs to reflect the change.

**Comment by sahat** [comment]
Sorry for the late reply, the change looks good to me, I am going to go ahead and merge it.

**Comment by sahat** [comment]
You can find the latest express-handlebars v3.1.0 on npm, which includes this change, as well as the updated handlebars v4.1.2 dependency.

**Comment by calebolin** [comment]
This wasn't backwards-compatible. 😢

**Comment by jfbrennan** [comment]
@calebolin how so?

Previously you had to `exphbs({defaultLayout: 'filename'})` and you can continue to do that with the new version. If you `exphbs()` that works now as well with `defaultLayout` defaulting to 'main'

**Comment by UziTech** [comment]
express-handlebars could be used without a layout when using `exphbs()` which has to be changed to `exphbs({defaultLayout: null})` with this change.

This should bump the major version #253

**Comment by calebolin** [comment]
@jfbrennan exactly what @UziTech said

**Comment by jfbrennan** [comment]
No layout at all...never had that use case 🤔

**Comment by calebolin** [comment]
IMHO it doesn't matter whether a use case can be imagined. If the API supports it, and a release breaks that API, it should be a major version bump.

**Comment by smebberson** [comment]
Yes, this should have been a major version bump.

**Comment by guanzo** [comment]
Broke for me too

**Comment by donmccurdy** [comment]
This PR broke an example application I provide to other developers, and I've received complaints from those developers. Code that previously worked without a layout now throws an error, without intentionally updating this dependency:

```
Error: ENOENT: no such file or directory, open '<project-path>/views/layouts/main.hbs'
```

Please consider reverting the change in the 3.x lifecycle and re-releasing it in a 4.x release, although that's yet another API-breaking change so I could see the argument for leaving this alone now that it's done. See https://semver.org/. Thanks!

**Comment by twbartel** [comment]
I have the same issue that @donmccurdy has, and that is currently causing me a lot of unnecessary work. Therefore, I support his request.

**Comment by jfbrennan** [comment]
For those who were broken does @UziTech's `defaultLayout: null` not resolve your issues? 

I think the change is a positive one, but could have done my part to help the maintainers identify non-backwards compatible use cases.

**Comment by twbartel** [comment]
@jfbrennan Yes, it does resolve the issue. Of course, the code to adapt is fairly minimal and takes only 5 minutes. What was quite a bit of work, in my case, was:

- Figuring out what my clients complained about
- Figuring out why that happens, and which npm package to focus on
- Finding this discussion and understanding the issue
- Deciding on a way forward (pin version to 3.0 or go with 3.1 or something else?)
- Making a change to a training video
- Communicating the change

All in all, I estimate I lost 4-5 hours due to this change. I was rather unhappy with this, because it produced no value for anybody.

**Comment by kevfromireland** [comment]
Just encountered this breaking change today myself. 

FWIW, I really appreciate the effort you put into the library and the hassle it has saved me. The value it has provided me over the past year of using it nicely balances out the few hours today I had to burn :)

**Comment by PaulBehrendtVentoro** [comment]
hit us too, why still no 3.1.1? release this as v4

**Comment by kylepeeler** [comment]
This should have been a major version bump, breaking change... follow sem-ver...

**Pull request merged**
